### ISSUE TITLE
Heroku Problem

### ISSUE THREAD

**Issue by joeblack81** [kaspernj/php_process#6]
Hi Again, the gem was working fine on the local , but when deployed on Heroku I get this error 

2016-02-02T20:50:19.697267+00:00 app[web.1]: RuntimeError (PHP process wasnt started: /usr/bin/env: php5: No such file or directory
2016-02-02T20:50:19.697268+00:00 app[web.1]: ):
2016-02-02T20:50:19.697269+00:00 app[web.1]:   lib/php_process.rb:84:in `start_php_process'
2016-02-02T20:50:19.697269+00:00 app[web.1]:   lib/php_process.rb:232:in `check_php_process_startup'
2016-02-02T20:50:19.697270+00:00 app[web.1]:   lib/php_process.rb:39:in `initialize'

PHP is installed : 5.6.17
ini path : /app/.heroku/php/etc/php/php.ini

Please advice 
Thanks

**Comment by kaspernj** [comment]
Can you please supply the piece of code that starts the process?

Have you tried with a custom path as an argument:
```ruby
PhpProcess.new(cmd_php: "some/path/php") do |php|
```

**Comment by joeblack81** [comment]
[files.zip](https://github.com/kaspernj/php_process/files/116409/files.zip)

I have fixed the Path issue , Please have a look at my files , trying to call the php function ( exist in /lib) from my controller, i get this error.
#<RuntimeError: Didn't contain any data: ["<!--"]>
2016-02-03T21:03:51.764236+00:00 app[web.1]: /app/lib/php_process/communicator.rb:179:in `parse_line'
2016-02-03T21:03:51.764237+00:00 app[web.1]: /app/lib/php_process/communicator.rb:203:in `block in read_loop'
2016-02-03T21:03:51.764238+00:00 app[web.1]: /app/lib/php_process/communicator.rb:202:in `each_line'
2016-02-03T21:03:51.764239+00:00 app[web.1]: /app/lib/php_process/communicator.rb:202:in `read_loop'
2016-02-03T21:03:51.764240+00:00 app[web.1]: /app/lib/php_process/communicator.rb:189:in `block in start_read_loop'

Do I miss something ? Thanks in advance

**Comment by kaspernj** [comment]
It looks like you didn't paste the entire error message. There should be both a complete backtrace and a message.

**Comment by joeblack81** [comment]
sorry!
Processing by PaymentsController#index as HTML
2016-02-03T21:03:51.764227+00:00 app[web.1]: Error in read-loop-thread.
2016-02-03T21:03:51.764235+00:00 app[web.1]: #<RuntimeError: Didn't contain any data: ["<!--"]>
2016-02-03T21:03:51.764236+00:00 app[web.1]: /app/lib/php_process/communicator.rb:179:in `parse_line'
2016-02-03T21:03:51.764237+00:00 app[web.1]: /app/lib/php_process/communicator.rb:203:in `block in read_loop'
2016-02-03T21:03:51.764238+00:00 app[web.1]: /app/lib/php_process/communicator.rb:202:in `each_line'
2016-02-03T21:03:51.764239+00:00 app[web.1]: /app/lib/php_process/communicator.rb:202:in `read_loop'
2016-02-03T21:03:51.764240+00:00 app[web.1]: /app/lib/php_process/communicator.rb:189:in `block in start_read_loop'
2016-02-03T21:04:21.313276+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/payments" host=www.trycarriage.com request_id=c6b584eb-a0f1-4c4a-93c1-9e47ac1e6dfa fwd="37.231.221.25" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0
2016-02-03T21:04:22.853474+00:00 app[web.1]: E, [2016-02-03T21:04:22.853366 #3] ERROR -- : worker=0 PID:6 timeout (31s > 30s), killing
2016-02-03T21:04:22.991838+00:00 app[web.1]: I, [2016-02-03T21:04:22.991643 #43]  INFO -- : worker=0 ready
2016-02-03T21:04:22.864640+00:00 app[web.1]: E, [2016-02-03T21:04:22.864524 #3] ERROR -- : reaped #<Process::Status: pid 6 SIGKILL (signal 9)> worker=0

**Comment by kaspernj** [comment]
@joeblack81 It looks like your PHP code outputs. PHP process didn't like that. I have fixed it in the latest master. Use it like this in your Gemfile:

```ruby
gem "php_process", github: "kaspernj/php_process"
```

Run bundle afterwards. Look forward to hearing if this works out for you :-)

**Comment by joeblack81** [comment]
Thanks A lot , That works and Now I can see the error that coming from the PHP,
Here I include my log, I know it might be something not related to your gem, but I will be so appreciated if you can advice, what is this error about? what you suggest  to fix it.
my files are in the previous post.
Thank you so much 

Processing by PaymentsController#index as HTML
2016-02-04T18:25:52.336673+00:00 app[web.1]: [php_process] <!--
2016-02-04T18:25:52.336680+00:00 app[web.1]: [php_process] This merchant demo is published by Knet as a demonstration of the process
2016-02-04T18:25:52.336696+00:00 app[web.1]: [php_process] of Online Knet Payment Gateway Transactions. Note however that this is not
2016-02-04T18:25:52.336722+00:00 app[web.1]: [php_process] a fully running demo and there are parts that the merchant has to build him self.

2016-02-04T18:25:52.384848+00:00 app[web.1]: Completed 500 Internal Server Error in 221ms
2016-02-04T18:25:52.388722+00:00 app[web.1]: 
2016-02-04T18:25:52.388725+00:00 app[web.1]: PhpProcess::PhpError (Error Warning: unlink(/app/lib/resource.cgz): No such file or directory in "/app/lib/e24PaymentPipe.inc.php:564):
2016-02-04T18:25:52.388727+00:00 app[web.1]:   lib/e24PaymentPipe.inc.php(564): unlink('/app/lib/resour...')
2016-02-04T18:25:52.388728+00:00 app[web.1]:   lib/e24PaymentPipe.inc.php(547): e24PaymentPipe->createReadableZip()
2016-02-04T18:25:52.388728+00:00 app[web.1]:   lib/e24PaymentPipe.inc.php(333): e24PaymentPipe->getSecureSettings()
2016-02-04T18:25:52.388729+00:00 app[web.1]:   lib/buy.php(44): e24PaymentPipe->performPaymentInitialization()
2016-02-04T18:25:52.388730+00:00 app[web.1]:   app/controllers/payments_controller.rb:11:in `block in index'
2016-02-04T18:25:52.388731+00:00 app[web.1]:   app/controllers/payments_controller.rb:8:in `new'
2016-02-04T18:25:52.388731+00:00 app[web.1]:   app/controllers/payments_controller.rb:8:in `index'
2016-02-04T18:25:52.388732+00:00 app[web.1]:

**Comment by kaspernj** [comment]
The PHP error is raised, because the PHP code is trying to delete a file, that doesn't exist. The file should exist with a path called "/app/lib/resource.cgz". This is just a warning however.

I guess PhpProcess shouldn't treat PHP-warnings as exceptions though, but just show them in the console instead, since a warning wouldn't crash a normal PHP application. I will take a look at that later.

**Comment by joeblack81** [comment]
Thank you so much fro your quick response, I will be waiting for your update, as I am totally depending on This gem to finish my project :) 

Thanks again

**Comment by kaspernj** [comment]
@joeblack81 I think I have fixed it in the latest master.

`E_STRICT`, `E_NOTICE` & `E_WARNING` will just be written directly in `$stderr` instead.

**Comment by joeblack81** [comment]
Thank you again , When I run bundle install , I see  this 
Using php_process 0.0.12 from git://github.com/kaspernj/php_process.git (at master@88e801e)
is this the last commit ?
Cause I tried now and got the same error , I am afraid I didn't get your last commits

**Comment by kaspernj** [comment]
Try this:
```bash
bundle update php_process
```

**Comment by joeblack81** [comment]
AMAZING!! Every thing is GREAT now , Thanks to you

**Comment by kaspernj** [comment]
I am glad I could help :-)
